---
title: "Test"
format: html
---

```{r}
library(rvest)

page <- read_html("htmlTables/test.Rhtml")  # path to saved HTML
tables <- html_nodes(page, "table") %>% html_table(fill = TRUE)

tables_filtered <- tables[sapply(tables, function(tbl) nrow(tbl) > 1)]
head(tables_filtered[[1]])
```
```{r}
df <- tables_filtered[[1]]
df$Time <- as.numeric(df$Time)

# Plot histogram of times
ggplot(df, aes(x = Time)) +
  geom_bar() +  
  labs(title = "Distribution of Times", x = "Time (seconds)", y = "Count")
```

```{r}
page <- read_html("htmlTables/MIAC/MIACIndoor2024.html")  # path to saved HTML
tables <- html_nodes(page, "table") %>% html_table(fill = TRUE)

indoor_2024 <- tables[sapply(tables, function(tbl) nrow(tbl) > 1)]


head(indoor_2024[[31]])

```
```{r}
  url <- str_c("htmlTables/MIAC/MIACIndoor", 2024,
                 ".html")
  page <- read_html(url)
  tables <- html_nodes(page, "table") %>% html_table(fill = TRUE)

  indoor_temp <- tables[sapply(tables, function(tbl) nrow(tbl) > 1)]
```


```{r}
all_miac <- list()
entry_index <- 1

for(i in(2021:2025)){
  url <- str_c("htmlTables/MIAC/MIACIndoor", i,
                 ".html")
  page <- read_html(url)
  tables <- html_nodes(page, "table") |>
    html_table(fill = TRUE)
  
  event_names <- page |>
  html_nodes("h3.font-weight-500") |>
  html_text(trim = TRUE)
  
  indoor_temp <- tables[sapply(tables, function(tbl) nrow(tbl) > 1)]
  
  for (j in 1:length(indoor_temp)) {
    indoor_temp[[j]] <- indoor_temp[[j]] |>
      mutate(Year = i) |>
      mutate(Event = event_names[[j]])
    
    
    all_miac[[entry_index]] <- indoor_temp[[j]]
    entry_index <- entry_index + 1
  }
}

all_miac_clean <- lapply(all_miac, function(df) {
  if ("Time" %in% names(df)) {
    df$Time <- as.character(df$Time)
  }
  return(df)
})

final_miac <- bind_rows(all_miac_clean[1:length(all_miac_clean)])
```

